[package]
name = "rust-game-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
mlua = { version = "0.10.5", features = ["lua54", "vendored"] }
once_cell = "1.21.3"
wgpu = "25.0"
winit = "0.30.11"
pollster = "0.3"
